Repository Ribbit-Network/ribbit-network-frog-software, pull requests merged in 2022-12, with the labels that each got.

#8 README: Added more organization info
  README.md
Labels: documentation

#13 Revert "ribbit.network: Set ribbit.local as the mDNS hostname"
  modules/ribbit/network.py
Labels: bug

#17 Implement the data model
  modules/main.py
  modules/ribbit/sensors/base.py
  modules/ribbit/sensors/board.py
  modules/ribbit/sensors/dps310.py
  modules/ribbit/sensors/gps.py
  modules/ribbit/sensors/scd30.py
Labels: enhancement
